const state={licenses:[],limits:[],risa:{observations:[],meta:{}},stations:{stations:[],meta:{}},map:null,markers:null,stationLayer:null,linkLayer:null,filtered:[],stationMap:null,stationMapLayer:null,weatherCache:new WeakMap()};
const LIMITS_URL='data/temperature-limits.json',LICENSE_URL='data/licenses.json',RISA_URL='data/risa-latest.json',RISA_STATIONS_URL='data/risa-stations.json';
const STALE_HOURS=3,WARNING_MARGIN_C=2;
function parseObsTime(st){if(!st?.obsDate||!st?.obsTime)return null;const d=new Date(`${st.obsDate}T${st.obsTime}+09:00`);return Number.isNaN(d.getTime())?null:d;}
function isStale(st){const d=parseObsTime(st);if(!d)return true;return (Date.now()-d.getTime())/36e5>STALE_HOURS;}
function tempStatus(temp,lim,st){if(!st||temp==null)return {key:'gray',label:'수온자료 없음'};if(!lim)return {key:'gray',label:'한계수온 없음'};const low=lim.low,high=lim.high;if((low!=null&&temp<low)||(high!=null&&temp>high))return {key:'red',label:'위험'};if((low!=null&&temp<=low+WARNING_MARGIN_C)||(high!=null&&temp>=high-WARNING_MARGIN_C))return {key:'yellow',label:'주의'};return {key:'green',label:'안전'};}
function matchLimit(f){const preferred=String(f.limit_species||'').trim();if(preferred){const m=state.limits.find(x=>x.species===preferred);if(m)return m;}let s=String(f['양식물']||'').replace(/\s+/g,'');if(s.includes('우렁쉥이'))s='멍게';else if(s.includes('전복'))s='참전복';return state.limits.find(x=>s.includes(x.species))||null;}
function haversine(lat1,lon1,lat2,lon2){const p=Math.PI/180,dLat=(lat2-lat1)*p,dLon=(lon2-lon1)*p;const a=Math.sin(dLat/2)**2+Math.cos(lat1*p)*Math.cos(lat2*p)*Math.sin(dLon/2)**2;return 6371*2*Math.atan2(Math.sqrt(a),Math.sqrt(1-a));}
// v6: 관측시각이 오래됐더라도 수온값이 존재하면 사용한다.
function nearestStation(lat,lon){if(lat==null||lon==null||!state.risa.observations?.length)return null;let best=null,bestD=Infinity;for(const st of state.risa.observations){if(st.lat==null||st.lon==null||st.waterTempC==null)continue;const d=haversine(lat,lon,st.lat,st.lon);if(d<bestD){bestD=d;best=st;}}return best?{...best,distanceKm:bestD}:null;}
function farmWeather(f){if(state.weatherCache.has(f))return state.weatherCache.get(f);const station=nearestStation(f.lat,f.lon),limit=matchLimit(f),temp=station?.waterTempC??null;const result={station,limit,temp,status:tempStatus(temp,limit,station)};state.weatherCache.set(f,result);return result;}
function escapeHtml(v){return String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));}
function badge(s){return `<span class="badge ${s.key}">${s.label}</span>`;}
function ageLabel(st){if(!st)return '';const d=parseObsTime(st);if(!d)return '관측시각 미상';const h=(Date.now()-d.getTime())/36e5;if(h<=STALE_HOURS)return '최근 관측';if(h<24)return `${Math.floor(h)}시간 전 관측`;const days=Math.floor(h/24);return `${days}일 전 관측`;}
function initMap(){state.map=L.map('map',{zoomControl:true}).setView([35.6,128.0],7);L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png',{attribution:'© OpenStreetMap contributors',maxZoom:19}).addTo(state.map);state.markers=L.markerClusterGroup({chunkedLoading:true,showCoverageOnHover:false});state.stationLayer=L.layerGroup();state.linkLayer=L.layerGroup();state.map.addLayer(state.markers);state.map.addLayer(state.stationLayer);state.map.addLayer(state.linkLayer);L.control.layers(null,{'양식장':state.markers,'통합 수온관측소':state.stationLayer},{collapsed:false}).addTo(state.map);}
function markerIcon(status){return L.divIcon({className:'',html:`<div class="marker-wrap"><div class="marker-dot ${status.key}"></div></div>`,iconSize:[18,18],iconAnchor:[9,9]});}
function stationIcon(st){return L.divIcon({className:'',html:`<div class="station-marker ${isStale(st)?'stale':''}">●</div>`,iconSize:[22,22],iconAnchor:[11,11]});}
function addStations(){state.stationLayer.clearLayers();for(const st of state.risa.observations||[]){if(st.lat==null||st.lon==null)continue;const m=L.marker([st.lat,st.lon],{icon:stationIcon(st),zIndexOffset:500});m.bindPopup(`<b>${escapeHtml(st.stationName)}</b><br>${escapeHtml(st.organization||'운영기관 미표기')}<br>표층수온 ${st.waterTempC==null?'-':st.waterTempC+'℃'}<br>${escapeHtml(st.obsDate)} ${escapeHtml(st.obsTime)}<br><small>${ageLabel(st)}${isStale(st)?' · 지연값도 사용 가능':''}</small>`);state.stationLayer.addLayer(m);}}
function addMarker(f){if(f.lat==null||f.lon==null)return;const wx=farmWeather(f);const m=L.marker([f.lat,f.lon],{icon:markerIcon(wx.status)});m.bindPopup(`<b>${escapeHtml(f['양식물']||'양식물 미기재')}</b><br>면허 ${escapeHtml(f['면허번호'])}<br>${wx.station?escapeHtml(wx.station.stationName):'사용 가능한 관측소 없음'} · ${wx.temp==null?'자료없음':wx.temp+'℃'}<br>${wx.status.label}`);m.on('click',()=>showDetail(f));state.markers.addLayer(m);}
function drawStationLink(f,st){state.linkLayer.clearLayers();if(!st||f.lat==null||f.lon==null)return;L.polyline([[f.lat,f.lon],[st.lat,st.lon]],{weight:3,dashArray:'7 7',opacity:.85}).addTo(state.linkLayer);L.circleMarker([st.lat,st.lon],{radius:8,weight:3,fillOpacity:.9}).bindTooltip(`적용 관측소: ${st.stationName}`).addTo(state.linkLayer);}
function showDetail(f){const wx=farmWeather(f),lim=wx.limit,st=wx.station,s=wx.status;drawStationLink(f,st);const remain=wx.temp!=null&&lim?.high!=null?(lim.high-wx.temp).toFixed(1):null;document.getElementById('detail').innerHTML=`<div class="detail"><div class="panel-head" style="padding:0 0 12px"><div><h2>${escapeHtml(f['양식물']||'양식물 미기재')}</h2><div class="sub">면허 ${escapeHtml(f['면허번호'])}</div></div>${badge(s)}</div><div class="kpi"><div class="box"><div class="label">현재 적용수온</div><div class="value">${wx.temp==null?'-':wx.temp+'℃'}</div></div><div class="box"><div class="label">고온 한계</div><div class="value">${lim?.high==null?'-':lim.high+'℃'}</div></div><div class="box"><div class="label">한계까지</div><div class="value">${remain==null?'-':remain+'℃'}</div></div><div class="box"><div class="label">관측소 거리</div><div class="value">${st?st.distanceKm.toFixed(1)+' km':'-'}</div></div></div><div class="status ${s.key}">${s.label}${lim?` · ${escapeHtml(lim.species)} 한계수온과 비교`:''}</div><table class="meta"><tr><th>시·도</th><td>${escapeHtml(f['시도'])}</td></tr><tr><th>시·군·구</th><td>${escapeHtml(f['시군구'])}</td></tr><tr><th>면허종류</th><td>${escapeHtml(f['면허종류']||'-')}</td></tr><tr><th>양식업종류</th><td>${escapeHtml(f['양식업종류'])}</td></tr><tr><th>양식물</th><td><b>${escapeHtml(f['양식물'])}</b></td></tr><tr><th>총면적</th><td>${escapeHtml(f['총면적']||'-')}</td></tr><tr><th>어장위치</th><td>${escapeHtml(f['어장위치'])}</td></tr><tr><th>도로명주소</th><td>${escapeHtml(f['도로명주소'])}</td></tr><tr><th>어업권자</th><td>${escapeHtml(f['어업권자'])}</td></tr><tr><th>소유형태</th><td>${escapeHtml(f['소유형태']||'-')}</td></tr><tr><th>면허기간</th><td>${escapeHtml(f['현재면허시작일'])} ~ ${escapeHtml(f['현재면허종료일'])}</td></tr><tr><th>적정수온</th><td>${lim?.optimal?escapeHtml(lim.optimal):'-'}</td></tr><tr><th>저온 / 고온 한계</th><td>${lim?(lim.low??'-')+'℃ / '+(lim.high??'-')+'℃':'-'}</td></tr><tr><th>적용 관측소</th><td>${st?escapeHtml(st.stationName):'사용 가능한 관측소 없음'}</td></tr><tr><th>운영기관</th><td>${st?escapeHtml(st.organization||'미표기'):'-'}</td></tr><tr><th>관측거리</th><td>${st?st.distanceKm.toFixed(2)+' km':'-'}</td></tr><tr><th>관측시각</th><td>${st?`${escapeHtml(st.obsDate)} ${escapeHtml(st.obsTime)} (${ageLabel(st)})`:'-'}</td></tr><tr><th>관측수심</th><td>${st?.surfaceDepthM==null?'-':st.surfaceDepthM+' m'}</td></tr></table><p class="note">관측값이 존재하면 관측 지연 여부와 관계없이 가장 가까운 통합 수온관측소의 표층수온을 적용합니다. 오래된 값은 관측시각을 반드시 함께 확인하세요.</p></div>`;document.getElementById('detail').classList.add('open');}
function renderSummary(){let c={green:0,yellow:0,red:0,gray:0};for(const f of state.licenses)c[farmWeather(f).status.key]++;document.getElementById('summary').innerHTML=`<span>🟢 안전 <b>${c.green.toLocaleString()}</b></span><span>🟡 주의 <b>${c.yellow.toLocaleString()}</b></span><span>🔴 위험 <b>${c.red.toLocaleString()}</b></span><span>⚪ 미판정 <b>${c.gray.toLocaleString()}</b></span>`;}
function renderList(){const q=document.getElementById('search').value.trim().toLowerCase(),p=document.getElementById('province').value,sp=document.getElementById('species').value;state.filtered=state.licenses.filter(f=>{const text=[f['면허번호'],f['양식물'],f['시도'],f['시군구'],f['도로명주소'],f['어업권자']].filter(Boolean).join(' ').toLowerCase();return(!q||text.includes(q))&&(!p||f['시도']===p)&&(!sp||String(f['양식물']||'').includes(sp));});const box=document.getElementById('list');box.innerHTML='';state.filtered.slice(0,200).forEach(f=>{const wx=farmWeather(f),d=document.createElement('div');d.className='item';d.innerHTML=`<div class="row"><div class="name">${escapeHtml(f['양식물']||'미기재')}</div>${badge(wx.status)}</div><div class="sub">면허 ${escapeHtml(f['면허번호'])} · ${escapeHtml(f['시군구']||'')}</div><div class="sub">${wx.station?escapeHtml(wx.station.stationName):'사용 가능한 관측소 없음'} · ${wx.temp==null?'-':wx.temp+'℃'} · ${wx.station?wx.station.distanceKm.toFixed(1)+'km':''}${wx.station&&isStale(wx.station)?' · 지연값':''}</div>`;d.onclick=()=>{if(f.lat!=null)state.map.setView([f.lat,f.lon],Math.max(state.map.getZoom(),11));showDetail(f);};box.appendChild(d);});document.getElementById('farmCount').textContent=`${state.filtered.length.toLocaleString()}건`;}
function buildFilters(){const provinces=[...new Set(state.licenses.map(x=>x['시도']).filter(Boolean))].sort((a,b)=>String(a).localeCompare(String(b),'ko'));provinces.forEach(v=>{document.getElementById('province').add(new Option(v,v));document.getElementById('statsProvince').add(new Option(v,v));});[...new Set(state.licenses.map(x=>x['양식물']).filter(Boolean))].sort((a,b)=>String(a).localeCompare(String(b),'ko')).forEach(v=>{if(v!=='0')document.getElementById('species').add(new Option(v,v));});}
function renderLimits(){const q=document.getElementById('limitSearch').value.trim();document.getElementById('limitsTable').innerHTML=state.limits.filter(x=>!q||x.species.includes(q)).map(x=>`<tr><td><b>${x.species}</b></td><td>${x.habitat}</td><td>${x.optimal}</td><td>${x.low==null?'-':x.low+'℃'}</td><td>${x.high==null?'-':x.high+'℃'}</td></tr>`).join('');}
function goMapPair(province,species){document.querySelector('.tab[data-tab="map"]').click();document.getElementById('province').value=province==='미기재'?'':province;document.getElementById('species').value=species==='미기재'?'':species;document.getElementById('search').value='';renderList();}
function buildProvinceSpeciesRows(){const groups=new Map();for(const f of state.licenses){let province=String(f['시도']??'').trim()||'미기재';let species=String(f['양식물']??'').trim();if(!species||species==='0')species='미기재';const key=province+'\u0001'+species;if(!groups.has(key))groups.set(key,{province,species,count:0,tempSum:0,tempN:0,green:0,yellow:0,red:0,gray:0,limit:null});const g=groups.get(key),wx=farmWeather(f);g.count++;if(wx.temp!=null){g.tempSum+=Number(wx.temp);g.tempN++;}g[wx.status.key]++;if(!g.limit&&wx.limit)g.limit=wx.limit;}return [...groups.values()].sort((a,b)=>a.province.localeCompare(b.province,'ko')||a.species.localeCompare(b.species,'ko'));}
function dominantStatus(g){const pairs=[['red',g.red],['yellow',g.yellow],['green',g.green],['gray',g.gray]].sort((a,b)=>b[1]-a[1]);return pairs[0][0];}
function renderStats(){const rows=buildProvinceSpeciesRows();const p=document.getElementById('statsProvince').value,q=document.getElementById('statsSpecies').value.trim().toLowerCase(),status=document.getElementById('statsStatus').value;const filtered=rows.filter(g=>(!p||g.province===p)&&(!q||g.species.toLowerCase().includes(q))&&(!status||g[status]>0));const provinces=new Set(rows.map(x=>x.province).filter(x=>x!=='미기재'));const species=new Set(rows.map(x=>x.species).filter(x=>x!=='미기재'));const judged=state.licenses.filter(f=>farmWeather(f).status.key!=='gray').length;document.getElementById('statsKpis').innerHTML=`<div class="stats-kpi"><div class="label">전체 양식장</div><div class="num">${state.licenses.length.toLocaleString()}</div></div><div class="stats-kpi"><div class="label">시·도</div><div class="num">${provinces.size.toLocaleString()}</div></div><div class="stats-kpi"><div class="label">양식품종 표기</div><div class="num">${species.size.toLocaleString()}</div></div><div class="stats-kpi"><div class="label">한계수온 판정 가능</div><div class="num">${judged.toLocaleString()}</div></div>`;document.getElementById('statsRowCount').textContent=`${filtered.length.toLocaleString()}개 시도·품종 조합`;document.getElementById('provinceSpeciesTable').innerHTML=filtered.map(g=>{const lim=g.limit,avg=g.tempN?(g.tempSum/g.tempN).toFixed(1)+'℃':'-';return `<tr class="stats-data-row" data-province="${escapeHtml(g.province)}" data-species="${escapeHtml(g.species)}"><td><b>${escapeHtml(g.province)}</b></td><td>${escapeHtml(g.species)}</td><td>${g.count.toLocaleString()}</td><td>${avg}</td><td>${lim?.optimal?escapeHtml(lim.optimal)+'℃':'-'}</td><td>${lim?.low==null?'-':lim.low+'℃'}</td><td>${lim?.high==null?'-':lim.high+'℃'}</td><td class="count green-txt">${g.green.toLocaleString()}</td><td class="count yellow-txt">${g.yellow.toLocaleString()}</td><td class="count red-txt">${g.red.toLocaleString()}</td><td class="count gray-txt">${g.gray.toLocaleString()}</td></tr>`;}).join('')||'<tr><td colspan="11" class="empty-cell">조건에 맞는 현황이 없습니다.</td></tr>';document.querySelectorAll('#provinceSpeciesTable .stats-data-row').forEach((el,i)=>el.onclick=()=>goMapPair(filtered[i].province,filtered[i].species));}
function initStationMap(){if(state.stationMap)return;state.stationMap=L.map('stationMap',{zoomControl:true}).setView([35.6,128.0],7);L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png',{attribution:'© OpenStreetMap contributors',maxZoom:19}).addTo(state.stationMap);state.stationMapLayer=L.layerGroup().addTo(state.stationMap);}
function stationMapIcon(st){return L.divIcon({className:'',html:`<div class="station-map-icon ${isStale(st)?'stale':''}">수온</div>`,iconSize:[26,26],iconAnchor:[13,13]});}
function stationPopup(st){return `<b>${escapeHtml(st.stationName)}</b><br>운영기관 <b>${escapeHtml(st.organization||'미표기')}</b><br>표층수온 <b>${st.waterTempC==null?'-':st.waterTempC+'℃'}</b>${st.middleTempC!=null?` · 중층 ${st.middleTempC}℃`:''}${st.bottomTempC!=null?` · 저층 ${st.bottomTempC}℃`:''}<br>${escapeHtml(st.obsDate||'-')} ${escapeHtml(st.obsTime||'')}<br>해역 ${escapeHtml(st.seaArea||'-')}<br><small>${ageLabel(st)}${isStale(st)&&st.waterTempC!=null?' · 오래된 값도 매칭에 사용':''}</small>`;}
function buildStationFilters(){const obs=state.risa.observations||[];const orgEl=document.getElementById('stationOrg'),seaEl=document.getElementById('stationSea');if(!orgEl||!seaEl)return;const orgs=[...new Set(obs.map(x=>x.organization||'미표기').filter(Boolean))].sort((a,b)=>String(a).localeCompare(String(b),'ko'));const seas=[...new Set(obs.map(x=>x.seaArea).filter(Boolean))].sort((a,b)=>String(a).localeCompare(String(b),'ko'));orgEl.innerHTML='<option value="">전체 운영기관</option>'+orgs.map(v=>`<option value="${escapeHtml(v)}">${escapeHtml(v)}</option>`).join('');seaEl.innerHTML='<option value="">전체 해역</option>'+seas.map(v=>`<option value="${escapeHtml(v)}">${escapeHtml(v)}</option>`).join('');}
function renderStationNetwork(){initStationMap();state.stationMapLayer.clearLayers();const all=state.risa.observations||[],org=document.getElementById('stationOrg')?.value||'',sea=document.getElementById('stationSea')?.value||'',q=(document.getElementById('stationSearch')?.value||'').trim().toLowerCase();const obs=all.filter(st=>(!org||(st.organization||'미표기')===org)&&(!sea||st.seaArea===sea)&&(!q||[st.stationName,st.organization,st.seaArea].filter(Boolean).join(' ').toLowerCase().includes(q)));const usable=obs.filter(x=>x.waterTempC!=null),stale=usable.filter(isStale).length;document.getElementById('stationCount').textContent=`${obs.length.toLocaleString()} / ${all.length.toLocaleString()}개소`;document.getElementById('stationSummary').innerHTML=`<div>표시 관측소<b>${obs.length.toLocaleString()}</b></div><div>표층수온 있음<b>${usable.length.toLocaleString()}</b></div>`;const list=document.getElementById('stationList');list.innerHTML='';for(const st of obs){if(st.lat!=null&&st.lon!=null){const m=L.marker([st.lat,st.lon],{icon:stationMapIcon(st)}).bindPopup(stationPopup(st));state.stationMapLayer.addLayer(m);}const d=document.createElement('div');d.className='station-item'+(isStale(st)?' stale':'');d.innerHTML=`<div class="top"><span class="name">${escapeHtml(st.stationName)}</span><span class="temp">${st.waterTempC==null?'-':st.waterTempC+'℃'}</span></div><div class="station-org">${escapeHtml(st.organization||'운영기관 미표기')} · ${escapeHtml(st.seaArea||'해역 미표기')}</div><div class="sub">${escapeHtml(st.obsDate||'-')} ${escapeHtml(st.obsTime||'')} · ${ageLabel(st)}</div>`;d.onclick=()=>{if(st.lat!=null&&st.lon!=null){state.stationMap.setView([st.lat,st.lon],11);L.popup().setLatLng([st.lat,st.lon]).setContent(stationPopup(st)).openOn(state.stationMap);}};list.appendChild(d);}if(!obs.length)list.innerHTML='<div class="empty" style="padding:20px">조건에 맞는 관측소가 없습니다.</div>';}
async function load(){const [lic,lim,risa,stations]=await Promise.all([fetch(LICENSE_URL).then(r=>r.json()),fetch(LIMITS_URL).then(r=>r.json()),fetch(RISA_URL+'?v='+Date.now()).then(r=>r.json()),fetch(RISA_STATIONS_URL+'?v='+Date.now()).then(r=>r.json()).catch(()=>({stations:[],meta:{}}))]);state.licenses=lic;state.limits=lim;state.risa=risa||{observations:[],meta:{}};state.stations=stations||{stations:[],meta:{}};state.weatherCache=new WeakMap();initMap();buildFilters();buildStationFilters();renderLimits();renderList();renderSummary();state.licenses.forEach(addMarker);addStations();renderStats();renderStationNetwork();const usable=[...(state.risa.observations||[])].filter(x=>x.waterTempC!=null).sort((a,b)=>`${b.obsDate||''} ${b.obsTime||''}`.localeCompare(`${a.obsDate||''} ${a.obsTime||''}`));const newest=usable[0],totalStations=state.stations?.count||state.risa?.meta?.stationCount||state.risa.observations?.length||0;document.getElementById('updated').textContent=newest?`통합 수온관측망 ${totalStations.toLocaleString()}개소 · 표층수온 ${usable.length.toLocaleString()}개소 사용 · 최신 ${newest.obsDate} ${newest.obsTime}`:'사용 가능한 수온 데이터 없음';}
document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));b.classList.add('active');const tab=b.dataset.tab;document.querySelectorAll('.view').forEach(v=>v.classList.remove('active'));const ids={map:'mapView',stats:'statsView',stations:'stationsView',limits:'limitsView',about:'aboutView'};document.getElementById(ids[tab]||'mapView').classList.add('active');setTimeout(()=>{state.map?.invalidateSize();state.stationMap?.invalidateSize();},80);});
['search','province','species'].forEach(id=>document.getElementById(id).addEventListener(id==='search'?'input':'change',renderList));document.getElementById('searchBtn').onclick=renderList;document.getElementById('limitSearch').addEventListener('input',renderLimits);['statsProvince','statsSpecies','statsStatus'].forEach(id=>document.getElementById(id).addEventListener(id==='statsSpecies'?'input':'change',renderStats));['stationOrg','stationSea'].forEach(id=>document.getElementById(id).addEventListener('change',renderStationNetwork));document.getElementById('stationSearch').addEventListener('input',renderStationNetwork);
load().catch(err=>{console.error(err);document.getElementById('updated').textContent='데이터 로드 오류';});

// v8: panel collapse / mobile controls
(function initResponsivePanels(){
  const dash=document.querySelector('.dashboard');
  const stationDash=document.querySelector('.station-dashboard');
  const farmPanel=document.getElementById('farmPanel');
  const detail=document.getElementById('detail');
  const stationPanel=document.getElementById('stationPanel');
  const tabs=document.getElementById('tabs');
  const isMobile=()=>window.matchMedia('(max-width:720px)').matches;
  const resizeMaps=()=>setTimeout(()=>{state.map?.invalidateSize();state.stationMap?.invalidateSize();},240);
  function closeMobilePanels(){farmPanel?.classList.remove('mobile-open');detail?.classList.remove('open');stationPanel?.classList.remove('mobile-open');}
  document.getElementById('farmPanelToggle')?.addEventListener('click',()=>{if(isMobile()) farmPanel.classList.remove('mobile-open'); else dash.classList.add('farm-collapsed');resizeMaps();});
  document.getElementById('farmPanelOpen')?.addEventListener('click',()=>{dash.classList.remove('farm-collapsed');resizeMaps();});
  document.getElementById('detailPanelToggle')?.addEventListener('click',()=>{detail.classList.remove('open');if(!isMobile()) dash.classList.add('detail-collapsed');resizeMaps();});
  document.getElementById('detailPanelOpen')?.addEventListener('click',()=>{dash.classList.remove('detail-collapsed');detail.classList.add('open');resizeMaps();});
  document.getElementById('stationPanelToggle')?.addEventListener('click',()=>{if(isMobile()) stationPanel.classList.remove('mobile-open'); else stationDash.classList.add('list-collapsed');resizeMaps();});
  document.getElementById('stationPanelOpen')?.addEventListener('click',()=>{if(isMobile()) stationPanel.classList.add('mobile-open'); else stationDash.classList.remove('list-collapsed');resizeMaps();});
  document.getElementById('mobileFarmBtn')?.addEventListener('click',()=>{farmPanel.classList.toggle('mobile-open');detail.classList.remove('open');});
  document.getElementById('mobileDetailBtn')?.addEventListener('click',()=>{detail.classList.toggle('open');farmPanel.classList.remove('mobile-open');});
  document.getElementById('mobileMenuBtn')?.addEventListener('click',()=>tabs.classList.toggle('mobile-open'));
  document.querySelectorAll('.tab').forEach(btn=>btn.addEventListener('click',()=>{tabs.classList.remove('mobile-open');if(isMobile())closeMobilePanels();}));
  window.addEventListener('resize',resizeMaps);
  // Mobile starts map-first: side panels remain hidden until requested.
  if(isMobile()) closeMobilePanels();
})();
