const state={licenses:[],limits:[],risa:{observations:[],meta:{}},map:null,markers:null,stationLayer:null,linkLayer:null,filtered:[]};
const LIMITS_URL='data/temperature-limits.json', LICENSE_URL='data/licenses.json', RISA_URL='data/risa-latest.json';
const STALE_HOURS=3, WARNING_MARGIN_C=2;
function parseObsTime(st){if(!st?.obsDate||!st?.obsTime)return null;const d=new Date(`${st.obsDate}T${st.obsTime}+09:00`);return Number.isNaN(d.getTime())?null:d;}
function isStale(st){const d=parseObsTime(st);if(!d)return true;return (Date.now()-d.getTime())/36e5>STALE_HOURS;}
function tempStatus(temp,lim,st){if(!st||temp==null)return {key:'gray',label:'수온자료 없음'};if(isStale(st))return {key:'gray',label:'관측 지연'};if(!lim)return {key:'gray',label:'한계수온 없음'};const low=lim.low,high=lim.high;if((low!=null&&temp<low)||(high!=null&&temp>high))return {key:'red',label:'위험'};if((low!=null&&temp<=low+WARNING_MARGIN_C)||(high!=null&&temp>=high-WARNING_MARGIN_C))return {key:'yellow',label:'주의'};return {key:'green',label:'안전'};}
function matchLimit(f){const preferred=String(f.limit_species||'').trim();if(preferred){const m=state.limits.find(x=>x.species===preferred);if(m)return m;}let s=String(f['양식물']||'').replace(/\s+/g,'');if(s.includes('우렁쉥이'))s='멍게';else if(s.includes('전복'))s='참전복';return state.limits.find(x=>s.includes(x.species))||null;}
function haversine(lat1,lon1,lat2,lon2){const p=Math.PI/180,dLat=(lat2-lat1)*p,dLon=(lon2-lon1)*p;const a=Math.sin(dLat/2)**2+Math.cos(lat1*p)*Math.cos(lat2*p)*Math.sin(dLon/2)**2;return 6371*2*Math.atan2(Math.sqrt(a),Math.sqrt(1-a));}
function nearestStation(lat,lon){if(lat==null||lon==null||!state.risa.observations?.length)return null;let best=null,bestD=Infinity;for(const st of state.risa.observations){if(st.lat==null||st.lon==null||st.waterTempC==null||isStale(st))continue;const d=haversine(lat,lon,st.lat,st.lon);if(d<bestD){bestD=d;best=st;}}return best?{...best,distanceKm:bestD}:null;}
function farmWeather(f){const station=nearestStation(f.lat,f.lon),limit=matchLimit(f),temp=station?.waterTempC??null;return {station,limit,temp,status:tempStatus(temp,limit,station)};}
function escapeHtml(v){return String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));}
function badge(s){return `<span class="badge ${s.key}">${s.label}</span>`;}
function initMap(){state.map=L.map('map',{zoomControl:true}).setView([35.6,128.0],7);L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png',{attribution:'© OpenStreetMap contributors',maxZoom:19}).addTo(state.map);state.markers=L.markerClusterGroup({chunkedLoading:true,showCoverageOnHover:false});state.stationLayer=L.layerGroup();state.linkLayer=L.layerGroup();state.map.addLayer(state.markers);state.map.addLayer(state.stationLayer);state.map.addLayer(state.linkLayer);L.control.layers(null,{'양식장':state.markers,'NIFS 관측소':state.stationLayer},{collapsed:false}).addTo(state.map);}
function markerIcon(status){return L.divIcon({className:'',html:`<div class="marker-wrap"><div class="marker-dot ${status.key}"></div></div>`,iconSize:[18,18],iconAnchor:[9,9]});}
function stationIcon(st){const stale=isStale(st);return L.divIcon({className:'',html:`<div class="station-marker ${stale?'stale':''}">●</div>`,iconSize:[22,22],iconAnchor:[11,11]});}
function addStations(){state.stationLayer.clearLayers();for(const st of state.risa.observations||[]){if(st.lat==null||st.lon==null)continue;const m=L.marker([st.lat,st.lon],{icon:stationIcon(st),zIndexOffset:500});m.bindPopup(`<b>NIFS ${escapeHtml(st.stationName)}</b><br>표층수온 ${st.waterTempC==null?'-':st.waterTempC+'℃'}<br>${escapeHtml(st.obsDate)} ${escapeHtml(st.obsTime)}${isStale(st)?'<br><b>⚠ 관측 지연</b>':''}`);state.stationLayer.addLayer(m);}}
function addMarker(f){if(f.lat==null||f.lon==null)return;const wx=farmWeather(f);const m=L.marker([f.lat,f.lon],{icon:markerIcon(wx.status)});m.bindPopup(`<b>${escapeHtml(f['양식물']||'양식물 미기재')}</b><br>면허 ${escapeHtml(f['면허번호'])}<br>${wx.station?escapeHtml(wx.station.stationName):'사용 가능한 관측소 없음'} · ${wx.temp==null?'자료없음':wx.temp+'℃'}<br>${wx.status.label}`);m.on('click',()=>showDetail(f));state.markers.addLayer(m);}
function drawStationLink(f,st){state.linkLayer.clearLayers();if(!st||f.lat==null||f.lon==null)return;L.polyline([[f.lat,f.lon],[st.lat,st.lon]],{weight:3,dashArray:'7 7',opacity:.85}).addTo(state.linkLayer);L.circleMarker([st.lat,st.lon],{radius:8,weight:3,fillOpacity:.9}).bindTooltip(`적용 관측소: ${st.stationName}`).addTo(state.linkLayer);}
function showDetail(f){const wx=farmWeather(f),lim=wx.limit,st=wx.station,s=wx.status;drawStationLink(f,st);const remain=wx.temp!=null&&lim?.high!=null?(lim.high-wx.temp).toFixed(1):null;document.getElementById('detail').innerHTML=`<div class="detail"><div class="panel-head" style="padding:0 0 12px"><div><h2>${escapeHtml(f['양식물']||'양식물 미기재')}</h2><div class="sub">면허 ${escapeHtml(f['면허번호'])}</div></div>${badge(s)}</div>
<div class="kpi"><div class="box"><div class="label">현재 수온</div><div class="value">${wx.temp==null?'-':wx.temp+'℃'}</div></div><div class="box"><div class="label">고온 한계</div><div class="value">${lim?.high==null?'-':lim.high+'℃'}</div></div><div class="box"><div class="label">한계까지</div><div class="value">${remain==null?'-':remain+'℃'}</div></div><div class="box"><div class="label">관측소 거리</div><div class="value">${st?st.distanceKm.toFixed(1)+' km':'-'}</div></div></div>
<div class="status ${s.key}">${s.label}${lim?` · ${escapeHtml(lim.species)} 한계수온과 비교`:''}</div>
<table class="meta"><tr><th>시·도</th><td>${escapeHtml(f['시도'])}</td></tr><tr><th>시·군·구</th><td>${escapeHtml(f['시군구'])}</td></tr><tr><th>면허종류</th><td>${escapeHtml(f['면허종류']||'-')}</td></tr><tr><th>양식업종류</th><td>${escapeHtml(f['양식업종류'])}</td></tr><tr><th>양식물</th><td><b>${escapeHtml(f['양식물'])}</b></td></tr><tr><th>총면적</th><td>${escapeHtml(f['총면적']||'-')}</td></tr><tr><th>어장위치</th><td>${escapeHtml(f['어장위치'])}</td></tr><tr><th>도로명주소</th><td>${escapeHtml(f['도로명주소'])}</td></tr><tr><th>어업권자</th><td>${escapeHtml(f['어업권자'])}</td></tr><tr><th>소유형태</th><td>${escapeHtml(f['소유형태']||'-')}</td></tr><tr><th>면허기간</th><td>${escapeHtml(f['현재면허시작일'])} ~ ${escapeHtml(f['현재면허종료일'])}</td></tr><tr><th>적정수온</th><td>${lim?.optimal?escapeHtml(lim.optimal):'-'}</td></tr><tr><th>저온 / 고온 한계</th><td>${lim?(lim.low??'-')+'℃ / '+(lim.high??'-')+'℃':'-'}</td></tr><tr><th>NIFS 관측소</th><td>${st?escapeHtml(st.stationName):'사용 가능한 관측소 없음'}</td></tr><tr><th>관측거리</th><td>${st?st.distanceKm.toFixed(2)+' km':'-'}</td></tr><tr><th>관측시각</th><td>${st?`${escapeHtml(st.obsDate)} ${escapeHtml(st.obsTime)}`:'-'}</td></tr><tr><th>관측수심</th><td>${st?.surfaceDepthM==null?'-':st.surfaceDepthM+' m'}</td></tr></table>
<p class="note">점선은 선택한 양식장과 적용된 NIFS 관측소를 연결합니다. 3시간 이상 지난 관측값은 매칭에서 자동 제외합니다.</p></div>`;document.getElementById('detail').classList.add('open');}
function renderSummary(){let c={green:0,yellow:0,red:0,gray:0};for(const f of state.licenses)c[farmWeather(f).status.key]++;document.getElementById('summary').innerHTML=`<span>🟢 안전 <b>${c.green.toLocaleString()}</b></span><span>🟡 주의 <b>${c.yellow.toLocaleString()}</b></span><span>🔴 위험 <b>${c.red.toLocaleString()}</b></span><span>⚪ 미판정 <b>${c.gray.toLocaleString()}</b></span>`;}
function renderList(){const q=document.getElementById('search').value.trim().toLowerCase(),p=document.getElementById('province').value,sp=document.getElementById('species').value;state.filtered=state.licenses.filter(f=>{const text=[f['면허번호'],f['양식물'],f['시도'],f['시군구'],f['도로명주소'],f['어업권자']].filter(Boolean).join(' ').toLowerCase();return(!q||text.includes(q))&&(!p||f['시도']===p)&&(!sp||String(f['양식물']||'').includes(sp));});const box=document.getElementById('list');box.innerHTML='';state.filtered.slice(0,200).forEach(f=>{const wx=farmWeather(f),d=document.createElement('div');d.className='item';d.innerHTML=`<div class="row"><div class="name">${escapeHtml(f['양식물']||'미기재')}</div>${badge(wx.status)}</div><div class="sub">면허 ${escapeHtml(f['면허번호'])} · ${escapeHtml(f['시군구']||'')}</div><div class="sub">${wx.station?escapeHtml(wx.station.stationName):'사용 가능한 관측소 없음'} · ${wx.temp==null?'-':wx.temp+'℃'} · ${wx.station?wx.station.distanceKm.toFixed(1)+'km':''}</div>`;d.onclick=()=>{if(f.lat!=null)state.map.setView([f.lat,f.lon],Math.max(state.map.getZoom(),11));showDetail(f);};box.appendChild(d);});document.getElementById('farmCount').textContent=`${state.filtered.length.toLocaleString()}건`;}
function buildFilters(){[...new Set(state.licenses.map(x=>x['시도']).filter(Boolean))].sort().forEach(v=>document.getElementById('province').add(new Option(v,v)));[...new Set(state.licenses.map(x=>x['양식물']).filter(Boolean))].sort((a,b)=>String(a).localeCompare(String(b),'ko')).forEach(v=>{if(v!=='0')document.getElementById('species').add(new Option(v,v));});}
function renderLimits(){const q=document.getElementById('limitSearch').value.trim();document.getElementById('limitsTable').innerHTML=state.limits.filter(x=>!q||x.species.includes(q)).map(x=>`<tr><td><b>${x.species}</b></td><td>${x.habitat}</td><td>${x.optimal}</td><td>${x.low==null?'-':x.low+'℃'}</td><td>${x.high==null?'-':x.high+'℃'}</td></tr>`).join('');}
async function load(){const [lic,lim,risa]=await Promise.all([fetch(LICENSE_URL).then(r=>r.json()),fetch(LIMITS_URL).then(r=>r.json()),fetch(RISA_URL+'?v='+Date.now()).then(r=>r.json())]);state.licenses=lic;state.limits=lim;state.risa=risa||{observations:[],meta:{}};initMap();buildFilters();renderLimits();renderList();renderSummary();state.licenses.forEach(addMarker);addStations();const fresh=[...(state.risa.observations||[])].filter(x=>x.obsDate&&x.obsTime&&!isStale(x)).sort((a,b)=>`${b.obsDate} ${b.obsTime}`.localeCompare(`${a.obsDate} ${a.obsTime}`));const newest=fresh[0];const staleCount=(state.risa.observations||[]).filter(isStale).length;document.getElementById('updated').textContent=newest?`NIFS 표층수온 ${newest.obsDate} ${newest.obsTime} 기준 · 사용 ${fresh.length}개소${staleCount?` · 지연 ${staleCount}개소 제외`:''}`:'사용 가능한 실시간 수온 데이터 없음';}
document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));b.classList.add('active');const tab=b.dataset.tab;document.querySelectorAll('.view').forEach(v=>v.classList.remove('active'));document.getElementById(tab==='map'?'mapView':tab==='limits'?'limitsView':'aboutView').classList.add('active');setTimeout(()=>state.map?.invalidateSize(),50);});
['search','province','species'].forEach(id=>document.getElementById(id).addEventListener(id==='search'?'input':'change',renderList));document.getElementById('searchBtn').onclick=renderList;document.getElementById('limitSearch').addEventListener('input',renderLimits);
load().catch(err=>{console.error(err);document.getElementById('updated').textContent='데이터 로드 오류';});

// ===== v5: province/species overview + dedicated NIFS observation network map =====
state.stationMap=null; state.stationMapLayer=null;
function countBy(field){const m=new Map();for(const f of state.licenses){let v=String(f[field]??'').trim();if(!v||v==='0')v='미기재';m.set(v,(m.get(v)||0)+1);}return [...m.entries()].sort((a,b)=>b[1]-a[1]);}
function goMapFilter(type,value){document.querySelector('.tab[data-tab="map"]').click();if(type==='province'){document.getElementById('province').value=value==='미기재'?'':value;document.getElementById('species').value='';}else{document.getElementById('species').value=value==='미기재'?'':value;document.getElementById('province').value='';}document.getElementById('search').value='';renderList();}
function renderBarList(target,rows,type){const max=Math.max(1,...rows.map(x=>x[1]));document.getElementById(target).innerHTML=rows.map(([name,n])=>`<div class="bar-row" data-name="${escapeHtml(name)}"><div class="bar-name" title="${escapeHtml(name)}">${escapeHtml(name)}</div><div class="bar-track"><div class="bar-fill" style="width:${(n/max*100).toFixed(1)}%"></div></div><div class="bar-value">${n.toLocaleString()}건</div></div>`).join('');document.querySelectorAll(`#${target} .bar-row`).forEach((el,i)=>el.onclick=()=>goMapFilter(type,rows[i][0]));}
function renderStats(){const p=countBy('시도'),s=countBy('양식물');const withCoords=state.licenses.filter(f=>f.lat!=null&&f.lon!=null).length;const judged=state.licenses.filter(f=>farmWeather(f).status.key!=='gray').length;document.getElementById('statsKpis').innerHTML=`<div class="stats-kpi"><div class="label">전체 양식장</div><div class="num">${state.licenses.length.toLocaleString()}</div></div><div class="stats-kpi"><div class="label">시·도</div><div class="num">${p.filter(x=>x[0]!=='미기재').length.toLocaleString()}</div></div><div class="stats-kpi"><div class="label">양식물 표기 종류</div><div class="num">${s.filter(x=>x[0]!=='미기재').length.toLocaleString()}</div></div><div class="stats-kpi"><div class="label">현재 수온판정 가능</div><div class="num">${judged.toLocaleString()}</div></div>`;document.getElementById('provinceStatsCount').textContent=`${p.length}개 구분`;document.getElementById('speciesStatsCount').textContent=`${s.length}개 구분`;renderBarList('provinceStats',p,'province');renderBarList('speciesStats',s,'species');}
function initStationMap(){if(state.stationMap)return;state.stationMap=L.map('stationMap',{zoomControl:true}).setView([35.6,128.0],7);L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png',{attribution:'© OpenStreetMap contributors',maxZoom:19}).addTo(state.stationMap);state.stationMapLayer=L.layerGroup().addTo(state.stationMap);}
function stationMapIcon(st){return L.divIcon({className:'',html:`<div class="station-map-icon ${isStale(st)?'stale':''}">NIFS</div>`,iconSize:[26,26],iconAnchor:[13,13]});}
function stationPopup(st){return `<b>${escapeHtml(st.stationName)}</b><br>표층수온 <b>${st.waterTempC==null?'-':st.waterTempC+'℃'}</b><br>${escapeHtml(st.obsDate||'-')} ${escapeHtml(st.obsTime||'')}<br>해역 ${escapeHtml(st.seaArea||'-')} · 수심 ${st.surfaceDepthM==null?'-':st.surfaceDepthM+'m'}${isStale(st)?'<br><b>⚠ 관측 지연</b>':''}`;}
function renderStationNetwork(){initStationMap();state.stationMapLayer.clearLayers();const obs=state.risa.observations||[],fresh=obs.filter(x=>!isStale(x)&&x.waterTempC!=null),stale=obs.length-fresh.length;document.getElementById('stationCount').textContent=`${obs.length.toLocaleString()}개소`;document.getElementById('stationSummary').innerHTML=`<div>정상 관측<b>${fresh.length.toLocaleString()}</b></div><div>지연/결측<b>${stale.toLocaleString()}</b></div>`;const list=document.getElementById('stationList');list.innerHTML='';for(const st of obs){if(st.lat!=null&&st.lon!=null){const m=L.marker([st.lat,st.lon],{icon:stationMapIcon(st)}).bindPopup(stationPopup(st));state.stationMapLayer.addLayer(m);}const d=document.createElement('div');d.className='station-item'+(isStale(st)?' stale':'');d.innerHTML=`<div class="top"><span class="name">${escapeHtml(st.stationName)}</span><span class="temp">${st.waterTempC==null?'-':st.waterTempC+'℃'}</span></div><div class="sub">${escapeHtml(st.seaArea||'-')} · ${escapeHtml(st.obsDate||'-')} ${escapeHtml(st.obsTime||'')} ${isStale(st)?'· 관측 지연':''}</div>`;d.onclick=()=>{if(st.lat!=null&&st.lon!=null){state.stationMap.setView([st.lat,st.lon],11);L.popup().setLatLng([st.lat,st.lon]).setContent(stationPopup(st)).openOn(state.stationMap);}};list.appendChild(d);}}

// Extend v4 load/tab behavior without changing data files.
const _v5Load=load;
load=async function(){await _v5Load();renderStats();renderStationNetwork();};
// v4 already invoked load() above before this extension when parsed; ensure v5 panels render after that promise finishes.
window.addEventListener('load',()=>{const wait=()=>{if(state.licenses.length){renderStats();renderStationNetwork();}else setTimeout(wait,100)};wait();});
document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));b.classList.add('active');const tab=b.dataset.tab;document.querySelectorAll('.view').forEach(v=>v.classList.remove('active'));const ids={map:'mapView',stats:'statsView',stations:'stationsView',limits:'limitsView',about:'aboutView'};document.getElementById(ids[tab]||'mapView').classList.add('active');setTimeout(()=>{state.map?.invalidateSize();state.stationMap?.invalidateSize();},80);});
